import type { Metadata } from 'next'
import { Inter, Lexend, Playfair_Display } from 'next/font/google'

import { cn } from '@/lib/utils'

import './globals.css'
import Providers from '@/components/providers'
import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({
  variable: '--font-sans',
  subsets: ['latin']
})

const playfair = Playfair_Display({
  variable: '--font-serif',
  subsets: ['latin']
})

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'flex min-h-screen flex-col font-sans antialiased max-w-3xl mx-auto __variable_36bd41 __variable_e3a538',
          inter.variable,
          playfair.variable,
          lexend.variable
        )}
      >
        <Providers>
          <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
